### ISSUE TITLE
touch command before cat command. 

### ISSUE THREAD

**Issue by kiryteo** [NJACKWinterOfCode/lterm#13]
Currently, if the 'cat' command is used with hello.txt gives the output from the file. If the touch command is mentioned before the cat command in the list, user can create his/her own file and will have the option to check the output for both hello.txt and newly created file.

**Comment by sr6033** [comment]
This is already solved in the original repo.

**Comment by kiryteo** [comment]
I opened this issue as when I try to access the  https://sr6033.github.io/lterm/ from original repo, it shows cat before touch.
