### ISSUE TITLE
Executing the clear command doesn't update the arr array.

### ISSUE THREAD

**Issue by aryadas98** [NJACKWinterOfCode/lterm#2]
After executing the `clear` command, if one types `help` it shows that `clear` is `Not Completed`.

**Comment by sr6033** [comment]
Yes. The issue is from a latest commit by another fellow. I haven't got time to check out the code yet. Will have a look by this weekend. If you can debug it by then, send a PR.

**Comment by sachincool** [comment]
claiming this one :smiley:

**Comment by Logan1x** [comment]
@sr6033  reopening because the issue isn't solved yet.

**Comment by sr6033** [comment]
Yes. It isn't solved.

**Comment by sachincool** [comment]
@sr6033  check the comments of my PR.

**Comment by sr6033** [comment]
Yes. It is working. I was actually looking at my old repo which was not updated. Kudos. Great work. Also check out the original repo to see new updated issues.
