### ISSUE TITLE
Make it mobile responsive

### ISSUE THREAD

**Issue by sr6033** [NJACKWinterOfCode/lterm#4]
As of now the terminal is not fully mobile responsive. The top part of the terminal gets disfigured in mobiles. And also it opens in a full-screen mode, not responsive mode.
![screenshot from 2017-11-26 12-22-44](https://user-images.githubusercontent.com/15799589/33237827-adc8ff42-d2a4-11e7-8ccf-b661630ae83e.png)

**Comment by kiryteo** [comment]
I've added a PR regarding this issue, please look into it.
